# Generated by Django 4.1.3 on 2022-12-05 11:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('signin', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userlogin',
            name='proofimg',
        ),
    ]
