# Generated by Django 4.1.3 on 2022-12-05 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signin', '0002_remove_userlogin_proofimg'),
    ]

    operations = [
        migrations.AddField(
            model_name='userlogin',
            name='proofimg',
            field=models.ImageField(default=1, upload_to='pics'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userlogin',
            name='username',
            field=models.CharField(default=2, max_length=200),
            preserve_default=False,
        ),
    ]
