# Generated by Django 4.1.3 on 2022-12-06 06:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('signin', '0004_rename_confirmpassword_userlogin_confirmpassword_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userlogin',
            old_name='firs_tname',
            new_name='first_name',
        ),
    ]
