# Generated by Django 4.1.3 on 2022-12-06 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signin', '0005_rename_firs_tname_userlogin_first_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userlogin',
            name='proofimg',
        ),
        migrations.AddField(
            model_name='userlogin',
            name='adress1',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userlogin',
            name='adress2',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userlogin',
            name='city',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userlogin',
            name='grid',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='userlogin',
            name='mfileupload',
            field=models.FileField(default=1, upload_to='file'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userlogin',
            name='state',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userlogin',
            name='zip',
            field=models.CharField(default=1, max_length=8),
            preserve_default=False,
        ),
    ]
