# Generated by Django 4.1.3 on 2022-12-19 12:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('CRUD', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='crud',
            name='mobile',
            field=models.CharField(default=1, max_length=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='crud',
            name='position',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CRUD.position'),
        ),
    ]
